disp(['  PhiPsi Post-Processor'])  
disp([' -----------------------------------------------------------------------']) 
disp([' > RELEASE INFORMATION:                                                 ']) 
disp(['   PhiPsi Post Processor is used for plotting deformed or undeformed    ']) 
disp(['   mesh, contours of displacements and stresses at specified substep.   ']) 
disp([' -----------------------------------------------------------------------']) 
disp([' > Version 1.18.0   released on 2021-08-01                              ']) 
disp([' > AUTHOR: Fang Shi, Huaiyin Institute of Technology                    ']) 
disp([' > WEBSITE: http://PhiPsi.top                                           ']) 
disp([' > EMAIL: shifang@ustc.edu.cn or shifang@hyit.edu.cn                    ']) 
disp([' -----------------------------------------------------------------------']) 
disp(['                                                                        '])     